# Generated by Django 4.0.2 on 2022-02-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostrelations',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpostrelations',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
