# Generated by Django 4.0.2 on 2022-02-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userpostrelations_dislike_userpostrelations_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostrelations',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='userpostrelations',
            name='like',
        ),
        migrations.AddField(
            model_name='userpostrelations',
            name='like_or_dislike',
            field=models.PositiveSmallIntegerField(choices=[(0, 'dislike'), (1, 'like')], null=True),
        ),
    ]
