# Generated by Django 4.0.2 on 2022-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userpostrelations_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
