# Generated by Django 4.0.2 on 2022-02-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_last_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostrelations',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-19'),
            preserve_default=False,
        ),
    ]
